### ISSUE TITLE
Please add casting ability while riding Telaari Talbuk

### ISSUE THREAD

**Issue by arch1mede** [jp-ganis/JPS#425]
Currently when riding this mount that you get in Talador, you cannot cast and you have to dismount.

http://www.wowhead.com/spell=165803/telaari-talbuk

**Comment by arch1mede** [comment]
OK since this isn't being addressed, can someone at least tell me what I need to change to add if mounted start the rotation?

**Comment by pcmdgit** [comment]
Hi,


sorry got not and in the next days, maybe week, zero time . 

This should be in the jps.Cast function, jps.lua and in the line where you also find IsMounted() ... need here another check for " jps.buff("Telaari Talbuk") or something like that.

**Comment by arch1mede** [comment]
This is the only line with what you are describing:

	-- STOP Combat
	if (IsMounted() == true and jps.getConfigVal("dismount in combat") == 0) or UnitIsDeadOrGhost("player")==1 or jps.buff(L["Drink"],"player") then return end

Dont think I want it under stop combat?

But if it does need to go under it would it be:

	-- STOP Combat
	if (IsMounted() == true and jps.getConfigVal("dismount in combat") == 0) or UnitIsDeadOrGhost("player")==1 or jps.buff(L["Drink"],"player", "Telaari Talbuk") then return end
OR
-- STOP Combat
	if (IsMounted() == true and jps.getConfigVal("dismount in combat") == 0) or UnitIsDeadOrGhost("player")==1 or jps.buff(L["Drink"],"player") or jps.buff("Telaari Talbuk")then return end

**Comment by pcmdgit** [comment]
the comment is missleading... 

the if should be than like this:


    -- STOP Combat
    if ((IsMounted() == true and not jps.buff("Telaari Talbuk")) and jps.getConfigVal("dismount in combat") == 0 ) or UnitIsDeadOrGhost("player")==1 or jps.buff(L["Drink"],"player") then return end

**Comment by arch1mede** [comment]
OK thanks I will try that and let you know.

**Comment by arch1mede** [comment]
OK I just added that portion and it kills JPS, no errors but it no longer loads. I remove that part and it loads.

**Comment by arch1mede** [comment]
Works great, thank you. Closing
