### ISSUE TITLE
Req. and question about translation

### ISSUE THREAD

**Issue by shikulja** [jp-ganis/JPS#432]
req. need more strings
GUI, options panel, text messages.
and how to add to jplocal from Rotations spellnames?

i add to transl table

```
            -- Paladin spells
    ["Execution Sentence"] = "Смертный приговор"
    ["Avenging Wrath"] = "Гнев карателя"
    ["Rebuke"] = "Укор"
    ["Fist of Justice"] = "Кулак правосудия"
    ["Seal of Truth"] = "Печать правды"
    ["Templar's Verdict"] = "Вердикт храмовника"
```

and in  paladin_ret_pvp.lua
local L = MyLocalizationTable
    { L["Rebuke"], jps.shouldKick(rangedTarget) , rangedTarget },

because the English names of the spells do not work in rotation on Russian server

but error- 
Message: ..\AddOns\JPS\jplocal.lua line 162:
   '}' expected (to close '{' at line 159) near '['

**Comment by kirk24788** [comment]
Well...I guess you made a mistake in the jplocal.lua in Line 162 ;)
For one you are missing commas, if you have something like this it should work:

```
...
    elseif (GetLocale() == "ruRU") then
        MyLocalizationTable = setmetatable({
               ["Execution Sentence"] = "Смертный приговор",
               ["Avenging Wrath"] = "Гнев карателя",
               ["Rebuke"] = "Укор",
               ["Fist of Justice"] = "Кулак правосудия",
               ["Seal of Truth"] = "Печать правды",
               ["Templar's Verdict"] = "Вердикт храмовника",
        } , {__index = function(t, index) return index end})
    else
...
```
